version: '3.5'

services:
  oa-vue-my_build:
    build:
      context: .
      dockerfile: Dockerfile.stage
    container_name: 'oa-vue-my_build'
    volumes:
      - oa-vue-my_dist:/code/dist

  oa-vue-my_web:
    image: nginx
    ports:
      - 8001:80
    container_name: 'oa-vue-my_web'
    restart: unless-stopped
    volumes:
      - oa-vue-my_dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  oa-vue-my_dist: